# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0906640cd568c90e40d8338f2e49ec22d95fdc359b2627eecf5bcb6e79c7ceefef1a50bbb74e51531dd321e4da0e4e0b993efcdc582801da034166971b8e900c

test:
  secret_key_base: ae2c1be7daee98d895892c76c754268254ef301eb1541468165aceb907d8c079e50af45bb182de8ef5421f884052964813fa4500ab28a7a13015ba241b95a0c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
